### ISSUE TITLE
The checkboxes look different inside Cypress

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cyclope#5]
Real app in the browser:

<img width="761" alt="Screen Shot 2021-09-20 at 16 51 16" src="https://user-images.githubusercontent.com/2212006/134073972-5f9dc15f-9c69-49d7-add4-3053f5f81e4a.png">

the checkboxes are filled

In Cypress the checkboxes do not show up

<img width="791" alt="Screen Shot 2021-09-20 at 16 51 26" src="https://user-images.githubusercontent.com/2212006/134074013-4311e081-f3ee-4943-b269-7d815c9bf7c6.png">

**Comment by bahmutov** [comment]
Somehow this preload link sets the icon, but how does it get the blue background, I do not get
<img width="1031" alt="Screen Shot 2021-09-20 at 17 00 05" src="https://user-images.githubusercontent.com/2212006/134075075-1f0d6229-0b87-4c54-aeb3-bc72c1040735.png">

**Comment by bahmutov** [comment]
Found how the background is set for the checkbox

<img width="1381" alt="Screen Shot 2021-09-20 at 17 05 09" src="https://user-images.githubusercontent.com/2212006/134075647-3a70c129-1c9c-409a-9f18-3480751cc4d7.png">

Uses CSS

```css
/* CHECKED CARD */

.card .cb-container .cb-input:checked + .check {
  background: url("../assets/images/icon-check.svg"),
    linear-gradient(45deg, var(--clr-green), var(--clr-pink));
  background-repeat: no-repeat;
  background-position: center;
}
```
