### ISSUE TITLE
Handle serialize for checkboxes with image and linear gradient

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cyclope#6]
From #5 

style.css has (not working version is commented out)

```css
/* CHECKED CARD */

.card .cb-container .cb-input:checked + .check {
  /* background: url("../assets/images/icon-check.svg"),
    linear-gradient(45deg, var(--clr-green), var(--clr-pink)); */
  background: url('../assets/images/icon-check.svg');
  background-color: var(--clr-green);
  background-repeat: no-repeat;
  background-position: center;
}
```
